runtime: nodejs8
beta_settings:
  cloud_sql_instances: cedarqr-image-gen:us-central1:cedarqrimagegen 
env_variables:
  SQL_USER: postgres
  SQL_PASSWORD: postgres
  SQL_DATABASE: cedarqrimagegen_db
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: cedarqr-image-gen:us-central1:cedarqrimagegen
